executor         : slurm
jobs             : unlimited # Define total amount of parallel jobs that the pipeline can execute
cores            : 500 # Define total amount of cores that the pipeline can execute
latency-wait     : 60
keep-going       : true
use-singularity  : true
singularity-args : "--bind /scratch/qscd --bind /home --nv"
--use-conda      : true
retries          : 0    # Set the default number of retires if a job fails
default-resources: 
  mem_mb : 1000 # Set default ram for rules (cores is by default 1)
  runtime: 5    # Set the default walltime for jobs (in minutes)
  slurm_account: qscd # Slurm account. Adapt based on your group ID. Often is not required
  slurm_partition: irb_cpu_iclk