# ---  Location of configuration files and input. This MUST NOT be modified. ---
resources: config/resources.yaml
sample_sheet: config/samples.tsv

# --- General Settings ---
output_dir: "results"  # Main output directory
host_tmp_dir: "tmpdir" # Define the HOST path for temporary files. It will be created inside the out_dir path

# --- Reference Genome & Annotations ---
genome_build: "mm10" # Genome version available at UCSC goldenPath (see below `genome_fasta_url_template`)
# Blacklist regions. This pipeline contains v2 blacklist regions (https://github.com/Boyle-Lab/Blacklist)
# Included genomes: ce10, ce11, dm3, dm6, hg19, hg38, mm9, mm10
# If your genome is not in the previous list, you must specify the path to a custom blacklist file below
# Pipeline expects to be gzipped
custom_blacklist: "" 

# Note: Use hgdownload.cse.ucsc.edu for human builds like hg38 if .soe doesn't work
genome_fasta_url_template: "http://hgdownload.soe.ucsc.edu/goldenPath/{genome_build}/bigZips/{genome_build}.fa.gz"
chrom_sizes_url: "http://hgdownload.soe.ucsc.edu/goldenPath/{genome_build}/bigZips/{genome_build}.chrom.sizes"

# --- Chromosome Splits ---
# Directory containing fold_0.json, fold_1.json, ..., fold_4.json
splits_dir: "config/chr_splits"
folds: ["0", "1", "2", "3", "4"] # Corresponds to filenames like fold_0.json

# --- Tool Parameters ---
# MACS3 Parameters (adjust as needed)
macs3:
  macs3_gsize: "mm" # Mouse genome size estimate for MACS3
  macs3_pvalue: 0.01
  macs3_format: "BAMPE" # Or BAM if single-end
  model_params: "--nolambda --nomodel --shift -75 --extsize 150" # Model related parameters
  other_params: "--keep-dup all --call-summits" # Any other parameters you want to add

# ChromBPNet Preprocessing Parameters
chromnpnet_bias:
  peak_blacklist_extension: 1057 # DON'T CHANGE. This is based on the ChromBPNet Input size (2114bp). Change only if the tool updates it.
  assay_type: "ATAC" # Or "DNASE"
  extra_params: "" # Extra parameters for bias model

# ChromBPNet Training Parameters (Defaults from tutorial, adjust as needed)
chromnpnet_model:
  assay_type: "ATAC" # Or "DNASE"
  extra_params: "" # Extra parameters for bias model

# --- Docker Images ---
chrombpnet_container: "docker://kundajelab/chrombpnet:latest"
macs3_container: "docker://quay.io/biocontainers/macs3:3.0.3--py39h0699b22_0"
utils_container: "docker://quay.io/biocontainers/bedtools:2.31.1--h13024bc_3" # Example, might need ucsc-wiggletools or similar