# resources.yaml
# Resource configuration for the ChromBPNet Snakemake pipeline
# Runtime is specified in minutes.
# mem_mb is specified in megabytes (GB * 1000).
# cpu specifies the number of cores (adjust based on tool capabilities and cluster policy).
# retries specifies how many times a job should be resubmitted on failure (useful for transient issues).

get_chrom_sizes:
  runtime: 10
  mem_mb: 1000
  retries: 3

get_blacklist:
  runtime: 10
  mem_mb: 1000
  retries: 3

download_and_index_fasta:
  runtime: 60
  mem_mb: 10000
  retries: 3

# samtools sort resources are already optimized, not recommended to modify them.
merge_sort_index_bams:
  runtime: 120
  cpu: 7
  mem_mb: 60000
  retries: 0

merge_sort_index_bias_bams:
  runtime: 120
  cpu: 10
  mem_mb: 100000
  retries: 0

macs3_peak_calling_pooled:
  runtime: 60
  mem_mb: 20000
  cpu: 1
  retries: 0

filter_peaks_blacklist:
  runtime: 30
  mem_mb: 4000
  retries: 0

get_top_n_peaks:
  runtime: 30
  mem_mb: 8000
  retries: 0

chrombpnet_prep_nonpeaks:
  runtime: 240 
  mem_mb: 8000
  retries: 0

train_bias_model:
  runtime: 1400
  mem_mb: 80000
  cpu: 2
  gres: gpu:rtx3090:1
  slurm_partition: irb_gpu_3090
  retries: 0

train_chrombpnet:
  runtime: 1400
  mem_mb: 80000
  cpu: 2
  gres: gpu:rtx3090:1
  slurm_partition: irb_gpu_3090
  retries: 0

predict_chrombpnet:
  runtime: 360
  mem_mb: 64000
  cpu: 4
  # gpu: 1
  retries: 0

interpret_chrombpnet:
  runtime: 480
  mem_mb: 96000
  cpu: 4
  # gpu: 1
  retries: 0